apiVersion: v1
kind: Secret
metadata:
  name: taskboard-db-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: taskboard-db
type: Opaque
stringData:
  password: {{ .Values.auth.password | default "taskboard" }}
