apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: nats
data:
  nats.conf: |
    # NATS Server Configuration.
    port: 4222
    monitor_port: 8222

    # Logging.
    debug: false
    trace: false
    logtime: true

    # Limits.
    max_connections: 1000
    max_payload: 1MB
    max_pending: 64MB
